#melakukan percobaan mengimplementasi Input pada file
f = open ('inputPasienCovid.txt', 'w') 
nik = input ("Masukan NIK :")
nama = input("Masukan Nama : ")
alamat = input("Masukan Alamat : ")
umur = input("Masukan Usia : ")
jeniskelamin = input("Masukan Jenis Kelamin: ")
nohp = input("Masukan Nohp : ")
gejala = input("Masukan Gejala : ")
f.write ("NIK : " + nik + "\n") 
f.write ("Nama : " + nama + "\n") 
f.write ("Alamat : " + alamat + "\n")
f.write ("Umur : " + umur + "\n")
f.write ("Jenis Kelamin : " + jeniskelamin + "\n")
f.write ("No Hp : " + nohp + "\n")
f.write ("Gejala : " + gejala + "\n")
f.close()
f = open ('inputPasienCovid.txt') 
content = f.read()
print (content) 

f.close()
